set nocp incsearch
set cinoptions=:0,p0,t0
set cinwords=if,else,while,do,for,switch,case
set formatoptions=tcqr
set cindent
set number
syntax on

augroup filetypedetect
au BufNewFile,BufRead *.sc	setf sc
augroup END
